name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a standard Linux environment
    steps:
      # Step 1: Check out your repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the correct Python version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Or your project's python version

      # Step 3: Install Poetry and your project's dependencies
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install

      # Step 4: Run Odoc to generate the Markdown files
      - name: Generate docs from source code
        run: poetry run odoc .

      # Step 5: Build the MkDocs site and deploy it to the gh-pages branch
      - name: Deploy documentation to GitHub Pages
        uses: mikefarah/mkdocs-github-pages@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch to deploy to