name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Generate docs from source code
        run: poetry run odoc .
      
      # NEW STEP: Export dependencies for the deployment action
      - name: Export dependencies
        run: poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Deploy documentation to GitHub Pages
        # CORRECTED ACTION: Using the correct, modern action with the @v1 tag
        uses: mikefarah/mkdocs-github-pages@v1
        with:
          # The requirements file will be used to install mkdocs and plugins
          requirements_file: requirements.txt